#!/usr/bin/env python3
"""Classify SE papers using Claude claude-4-opus-20250514 (Opus 4.6) via litellm.

For each paper in the CSV generated by download_papers.py, determines:
  1. Whether the paper is a Mining Software Repositories (MSR) paper.
  2. Whether the paper claims to use causal inference methods or makes causal claims.

API keys are loaded from a .env file (e.g. ANTHROPIC_API_KEY=...).
Output: data/se_papers_classified.csv
"""

import argparse
import csv
import json
import os
import sys
import time

from dotenv import load_dotenv
import litellm
from litellm import completion
from litellm.exceptions import RateLimitError, APIError

from log_utils import setup_logging

INPUT_FILE = os.path.join("data", "se_papers_metadata.csv")
OUTPUT_FILE = os.path.join("data", "se_papers_classified.csv")

MODEL = "anthropic/claude-4-opus-20250514"
MAX_RETRIES = 5
BATCH_SIZE = 1  # one paper per request for accuracy

CLASSIFICATION_PROMPT = """\
You are a research paper classifier. Given a paper's title and abstract, \
answer two questions with structured JSON output.

**Question 1 – MSR paper?**
Is this a Mining Software Repositories (MSR) paper? MSR papers analyse data \
extracted from software repositories (e.g., version control, issue trackers, \
code review systems, CI/CD logs, package registries, Q&A sites like \
Stack Overflow) to discover empirical insights about software development \
processes, practices, or artifacts.

**Question 2 – Causal inference or causal claims?**
Does the paper claim to use a causal inference method or make causal claims?
This includes:
- Explicit causal inference methods: propensity score matching, \
  instrumental variables, difference-in-differences, regression \
  discontinuity, Granger causality, causal DAGs / Bayesian networks, \
  do-calculus, synthetic control, interrupted time series, etc.
- Implied causal language / claims: statements like "X causes Y", "X leads to Y", \
  "the effect of X on Y", "X increases/decreases Y" regardless of whether the paper \
   claims to use a causal inference method.

Respond ONLY with a JSON object (no markdown fences, no commentary):
{
  "is_msr": true/false,
  "msr_reason": "<one-sentence justification>",
  "has_causal": true/false,
  "causal_type": "method" | "claim" | "both" | "none",
  "causal_reason": "<one-sentence justification>"
}
"""

log = setup_logging()


def classify_paper(title: str, abstract: str) -> dict:
    """Send a single paper to Claude via litellm and return the parsed classification."""
    user_msg = f"**Title:** {title}\n\n**Abstract:** {abstract or '(no abstract available)'}"

    for attempt in range(MAX_RETRIES):
        try:
            resp = completion(
                model=MODEL,
                max_tokens=300,
                temperature=0,
                messages=[
                    {"role": "system", "content": CLASSIFICATION_PROMPT},
                    {"role": "user", "content": user_msg},
                ],
            )
            text = resp.choices[0].message.content.strip()
            if text.startswith("```"):
                text = text.split("\n", 1)[1].rsplit("```", 1)[0].strip()
            return json.loads(text)

        except RateLimitError:
            wait = min(2 ** (attempt + 3), 120)
            log.warning("Rate limited, waiting %ds …", wait)
            time.sleep(wait)
        except (json.JSONDecodeError, IndexError, KeyError) as e:
            log.warning("Parse error (attempt %d): %s", attempt + 1, e)
            if attempt == MAX_RETRIES - 1:
                return {
                    "is_msr": None,
                    "msr_reason": f"PARSE_ERROR: {e}",
                    "has_causal": None,
                    "causal_type": "none",
                    "causal_reason": f"PARSE_ERROR: {e}",
                }
            time.sleep(2)
        except APIError as e:
            wait = 5 * (attempt + 1)
            log.warning("API error (attempt %d): %s, retrying in %ds …", attempt + 1, e, wait)
            time.sleep(wait)

    return {
        "is_msr": None,
        "msr_reason": "MAX_RETRIES_EXCEEDED",
        "has_causal": None,
        "causal_type": "none",
        "causal_reason": "MAX_RETRIES_EXCEEDED",
    }


def load_already_done(output_path: str) -> set[str]:
    """Return set of titles already classified (for resumability)."""
    done = set()
    if os.path.exists(output_path):
        with open(output_path, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                done.add(row["title"])
    return done


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-i", "--input", default=INPUT_FILE, help="Input CSV (default: %(default)s)"
    )
    parser.add_argument(
        "-o", "--output", default=OUTPUT_FILE, help="Output CSV (default: %(default)s)"
    )
    parser.add_argument(
        "--limit", type=int, default=0, help="Process at most N papers (0 = all)"
    )
    args = parser.parse_args()

    load_dotenv()

    if not os.environ.get("ANTHROPIC_API_KEY"):
        log.error("ANTHROPIC_API_KEY not set in .env or environment.")
        sys.exit(1)

    with open(args.input, encoding="utf-8") as f:
        papers = list(csv.DictReader(f))
    log.info("Loaded %d papers from %s", len(papers), args.input)

    done_titles = load_already_done(args.output)
    remaining = [p for p in papers if p["title"] not in done_titles]
    if done_titles:
        log.info("Resuming — %d already classified, %d remaining", len(done_titles), len(remaining))

    if args.limit:
        remaining = remaining[: args.limit]
        log.info("Limiting to %d papers", len(remaining))

    out_fields = [
        "venue", "title", "abstract",
        "is_msr", "msr_reason",
        "has_causal", "causal_type", "causal_reason",
    ]
    write_header = not os.path.exists(args.output) or not done_titles
    out_fh = open(args.output, "a" if done_titles else "w", newline="", encoding="utf-8")
    writer = csv.DictWriter(out_fh, fieldnames=out_fields)
    if write_header:
        writer.writeheader()

    try:
        for i, paper in enumerate(remaining, 1):
            title = paper["title"]
            abstract = paper.get("abstract", "")
            venue = paper.get("venue", "")

            log.info("[%d/%d] %s — %.80s", i, len(remaining), venue, title)
            result = classify_paper(title, abstract)

            row = {
                "venue": venue,
                "title": title,
                "abstract": abstract,
                "is_msr": result.get("is_msr"),
                "msr_reason": result.get("msr_reason", ""),
                "has_causal": result.get("has_causal"),
                "causal_type": result.get("causal_type", "none"),
                "causal_reason": result.get("causal_reason", ""),
            }
            writer.writerow(row)
            out_fh.flush()

            msr_flag = "MSR" if result.get("is_msr") else "   "
            causal_flag = result.get("causal_type", "none").upper()
            log.info("        [%s] [causal: %s]", msr_flag, causal_flag)

    except KeyboardInterrupt:
        log.info("Interrupted — progress saved. Re-run to resume.")
    finally:
        out_fh.close()

    total_done = len(done_titles) + i if "i" in dir() else len(done_titles)
    log.info("Classified %d/%d papers → %s", total_done, len(papers), args.output)


if __name__ == "__main__":
    main()
