#!/usr/bin/env python3
"""Classify SE papers using Claude claude-4-opus-20250514 (Opus 4.6) via litellm.

For each paper in the CSV generated by download_papers.py, determines:
  1. Whether the paper is a Mining Software Repositories (MSR) paper.
  2. Whether the paper claims to use causal inference methods or makes causal claims.

API keys are loaded from a .env file (e.g. ANTHROPIC_API_KEY=...).
Classification columns are written back to the input CSV in-place.
"""

import argparse
import json
import os
import sys
import time

import pandas as pd
from dotenv import load_dotenv
import litellm
from litellm import completion
from litellm.exceptions import RateLimitError, APIError

from log_utils import setup_logging

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_CSV = os.path.join(PROJECT_ROOT, "data", "se_papers_metadata.csv")

MODEL = "anthropic/claude-4-opus-20250514"
MAX_RETRIES = 5

CLASSIFICATION_PROMPT = """\
You are a research paper classifier. Given a paper's title and abstract, \
answer two questions with structured JSON output.

**Question 1 – MSR paper?**
Is this a Mining Software Repositories (MSR) paper? MSR papers analyse data \
extracted from software repositories (e.g., version control, issue trackers, \
code review systems, CI/CD logs, package registries, Q&A sites like \
Stack Overflow) to discover empirical insights about software development \
processes, practices, or artifacts.

**Question 2 – Causal inference or causal claims?**
Does the paper claim to use a causal inference method or make causal claims?
This includes:
- Explicit causal inference methods: propensity score matching, \
  instrumental variables, difference-in-differences, regression \
  discontinuity, Granger causality, causal DAGs / Bayesian networks, \
  do-calculus, synthetic control, interrupted time series, etc.
- Implied causal language / claims: statements like "X causes Y", "X leads to Y", \
  "the effect of X on Y", "X increases/decreases Y" regardless of whether the paper \
   claims to use a causal inference method.

Respond ONLY with a JSON object (no markdown fences, no commentary):
{
  "is_msr": true/false,
  "msr_reason": "<one-sentence justification>",
  "has_causal": true/false,
  "causal_type": "method" | "claim" | "both" | "none",
  "causal_reason": "<one-sentence justification>"
}
"""

CLASSIFICATION_FIELDS = ["is_msr", "msr_reason", "has_causal", "causal_type", "causal_reason"]

log = setup_logging()


def classify_paper(title: str, abstract: str) -> dict:
    """Send a single paper to Claude via litellm and return the parsed classification."""
    user_msg = f"**Title:** {title}\n\n**Abstract:** {abstract or '(no abstract available)'}"

    for attempt in range(MAX_RETRIES):
        try:
            resp = completion(
                model=MODEL,
                max_tokens=300,
                temperature=0,
                messages=[
                    {"role": "system", "content": CLASSIFICATION_PROMPT},
                    {"role": "user", "content": user_msg},
                ],
            )
            text = resp.choices[0].message.content.strip()
            if text.startswith("```"):
                text = text.split("\n", 1)[1].rsplit("```", 1)[0].strip()
            return json.loads(text)

        except RateLimitError:
            wait = min(2 ** (attempt + 3), 120)
            log.warning("Rate limited, waiting %ds …", wait)
            time.sleep(wait)
        except (json.JSONDecodeError, IndexError, KeyError) as e:
            log.warning("Parse error (attempt %d): %s", attempt + 1, e)
            if attempt == MAX_RETRIES - 1:
                return {
                    "is_msr": None,
                    "msr_reason": f"PARSE_ERROR: {e}",
                    "has_causal": None,
                    "causal_type": "none",
                    "causal_reason": f"PARSE_ERROR: {e}",
                }
            time.sleep(2)
        except APIError as e:
            wait = 5 * (attempt + 1)
            log.warning("API error (attempt %d): %s, retrying in %ds …", attempt + 1, e, wait)
            time.sleep(wait)

    return {
        "is_msr": None,
        "msr_reason": "MAX_RETRIES_EXCEEDED",
        "has_causal": None,
        "causal_type": "none",
        "causal_reason": "MAX_RETRIES_EXCEEDED",
    }


def save_csv(df: pd.DataFrame, path: str):
    """Atomically overwrite the CSV (write to tmp then rename)."""
    tmp = path + ".tmp"
    df.to_csv(tmp, index=False)
    os.replace(tmp, path)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "csv_file", nargs="?", default=DEFAULT_CSV,
        help="CSV file to classify in-place (default: %(default)s)",
    )
    parser.add_argument(
        "--limit", type=int, default=0, help="Process at most N papers (0 = all)"
    )
    args = parser.parse_args()

    load_dotenv(os.path.join(PROJECT_ROOT, ".env"))

    if not os.environ.get("ANTHROPIC_API_KEY"):
        log.error("ANTHROPIC_API_KEY not set in .env or environment.")
        sys.exit(1)

    df = pd.read_csv(args.csv_file)
    log.info("Loaded %d papers from %s", len(df), args.csv_file)

    for col in CLASSIFICATION_FIELDS:
        if col not in df.columns:
            df[col] = pd.NA

    needs_classification = df["is_msr"].isna()
    done_count = int((~needs_classification).sum())
    todo_indices = df.index[needs_classification].tolist()

    if done_count:
        log.info("Resuming — %d already classified, %d remaining", done_count, len(todo_indices))

    if args.limit:
        todo_indices = todo_indices[: args.limit]
        log.info("Limiting to %d papers", len(todo_indices))

    classified = 0
    try:
        for seq, idx in enumerate(todo_indices, 1):
            row = df.loc[idx]
            title = str(row["title"])
            abstract = str(row.get("abstract", ""))
            venue = str(row.get("venue", ""))

            log.info("[%d/%d] %s — %.80s", seq, len(todo_indices), venue, title)
            result = classify_paper(title, abstract)

            df.at[idx, "is_msr"] = result.get("is_msr")
            df.at[idx, "msr_reason"] = result.get("msr_reason", "")
            df.at[idx, "has_causal"] = result.get("has_causal")
            df.at[idx, "causal_type"] = result.get("causal_type", "none")
            df.at[idx, "causal_reason"] = result.get("causal_reason", "")
            classified += 1

            msr_flag = "MSR" if result.get("is_msr") else "   "
            causal_flag = result.get("causal_type", "none").upper()
            log.info("        [%s] [causal: %s]", msr_flag, causal_flag)

            if classified % 10 == 0:
                save_csv(df, args.csv_file)
                log.info("Checkpoint saved (%d new classifications)", classified)

    except KeyboardInterrupt:
        log.info("Interrupted — saving progress …")
    finally:
        save_csv(df, args.csv_file)

    log.info("Classified %d new papers (%d/%d total) → %s",
             classified, done_count + classified, len(df), args.csv_file)


if __name__ == "__main__":
    main()
